services:
  #- type: pserv
  - type: web
    name: app
    runtime: docker
    region: singapore # optional (defaults to oregon)
    plan: free
    rootDir: ./
    
    healthCheckPath: /
    dockerfilePath: ./docker/php/Dockerfile
    #buildCommand: 'docker build -f ./docker/php/Dockerfile -t app .'
  
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: ${MYSQL_ROOT_PASSWORD}
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE}
      - key: MYSQL_USER
        value: ${MYSQL_USER}
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}
      - key: PORT
        value: 9000

  - type: web
    name: nginx
    runtime: nginx:1.25.0
    image:
      url: docker.io/nginx:1.25.0
      creds:
        fromRegistryCreds:
          name: my-credential-name
    buildCommand: cp ./docker/nginx/default.conf /etc/nginx/conf.d
    startCommand: nginx -g 'daemon off;'

#    image: 
#      url: 'nginx:1.25.0'
    #startCommand: "docker run -d -p 80:80 nginx:1.25.0"
    #ports: # field ports not found in type file.Service
    #- 10000
#    envVars:
      #disks: #field disks not found in type file.Service
      #- name: src
        #mountPath: /var/www/html
      #disks: #field disks not found in type file.Service
      #- name: src
        #mountPath: /var/www/html
  #- type: pserv
  #  name: mysql
  #  runtime: docker
  #  image: 
  #    url: 'mysql:8.0'
    #startCommand: "docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} -e MYSQL_DATABASE=${MYSQL_DATABASE} -e MYSQL_USER=${MYSQL_USER} -e MYSQL_PASSWORD=${MYSQL_PASSWORD} mysql:8.0"
  #  envVars:
  #    - key: MYSQL_ROOT_PASSWORD
  #      value: ${MYSQL_ROOT_PASSWORD}
  #    - key: MYSQL_DATABASE
  #      value: ${MYSQL_DATABASE}
  #    - key: MYSQL_USER
  #      value: ${MYSQL_USER}
  #    - key: MYSQL_PASSWORD
  #      value: ${MYSQL_PASSWORD}
      #disks: #field disks not found in type file.Service
      #- name: mysqldata
        #mountPath: /var/lib/mysql

