
#NGINX-------------------------------------------------------------
# ベースとなるイメージを指定
FROM nginx:1.25.0

# 独自のphp.iniファイルをコンテナ内にコピー
COPY ./docker/nginx/default.conf /etc/nginx/conf.d

# 作業ディレクトリを設定
#WORKDIR /var/www/html


#NGINX----------------------------------------------------------------


# アプリケーションのソースコードをコンテナにコピー
#COPY ./src /var/www/html
